CREATE TABLE `users` ( 
    `ID` MEDIUMINT NOT NULL AUTO_INCREMENT, 
    `userID` INT NOT NULL , 
    `username` VARCHAR(50) NOT NULL ,
    `password` VARCHAR(50) NOT NULL , 
    `Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(ID));


